### ISSUE TITLE
TemplateAssertionError after updating

### ISSUE THREAD

**Issue by rpatel3001** [alexandrevicenzi/Flex#167]
I started using the v2.2 (b3bd590) commit found in the pelican-themes repo. After upgrading to latest (f9bce8dd), I get the following trace with `pelican -vD content`. Resolved by rolling back 1 commit to fd296e57. 

```
-> Writing /opt/blog/output/feeds/all.atom.xml
CRITICAL: TemplateAssertionError: no test named 'eq'                                                      
Traceback (most recent call last):                                                                        
  File "/usr/local/bin/pelican", line 11, in <module>                                                     
    sys.exit(main())                                                                                      
  File "/usr/local/lib/python3.4/dist-packages/pelican/__init__.py", line 623, in main                    
    pelican.run()                                                                                         
  File "/usr/local/lib/python3.4/dist-packages/pelican/__init__.py", line 190, in run                     
    p.generate_output(writer)                                                                             
  File "/usr/local/lib/python3.4/dist-packages/pelican/generators.py", line 689, in generate_output       
    self.generate_pages(writer)                                                                           
  File "/usr/local/lib/python3.4/dist-packages/pelican/generators.py", line 600, in generate_pages        
    self.generate_direct_templates(write)                                                                 
  File "/usr/local/lib/python3.4/dist-packages/pelican/generators.py", line 551, in generate_direct_templa
tes                                                                                                       
    page_name=os.path.splitext(save_as)[0], url=url)                                                      
  File "/usr/local/lib/python3.4/dist-packages/pelican/writers.py", line 248, in write_file               
    page.save_as, override_output)                                                                        
  File "/usr/local/lib/python3.4/dist-packages/pelican/writers.py", line 186, in _write_file              
    output = template.render(localcontext)                                                                
  File "/usr/local/lib/python3.4/dist-packages/jinja2/environment.py", line 989, in render                
    return self.environment.handle_exception(exc_info, True)                                              
  File "/usr/local/lib/python3.4/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)                                                                      
  File "/usr/local/lib/python3.4/dist-packages/jinja2/_compat.py", line 37, in reraise                    
    raise value.with_traceback(tb)                                                                        
  File "/opt/blog/themes/Flex/templates/base.html", line 127, in template                                 
    <a {% if name is eq 'mastodon' %}rel="me"{% endif %} class="sc-{{ name }}" href="{{ link }}" target="_
blank">                                                                                                   
  File "/usr/local/lib/python3.4/dist-packages/jinja2/environment.py", line 986, in render                
    return concat(self.root_render_func(self.new_context(vars)))                                          
  File "/opt/blog/themes/Flex/templates/index.html", line 1, in top-level template code                   
    {% extends "base.html" %}                                                                             
  File "/usr/local/lib/python3.4/dist-packages/jinja2/environment.py", line 754, in handle_exception      
    reraise(exc_type, exc_value, tb)                                                                      
  File "/usr/local/lib/python3.4/dist-packages/jinja2/_compat.py", line 37, in reraise                    
    raise value.with_traceback(tb)                                                                        
  File "/opt/blog/themes/Flex/templates/base.html", line 127, in template                                 
    <a {% if name is eq 'mastodon' %}rel="me"{% endif %} class="sc-{{ name }}" href="{{ link }}" target="_blank">
  File "/usr/local/lib/python3.4/dist-packages/jinja2/environment.py", line 515, in _generate            
    return generate(source, self, name, filename, defer_init=defer_init)                                 
  File "/usr/local/lib/python3.4/dist-packages/jinja2/compiler.py", line 62, in generate                 
    generator.visit(node)
  File "/usr/local/lib/python3.4/dist-packages/jinja2/visitor.py", line 38, in visit                     
    return f(node, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jinja2/compiler.py", line 816, in visit_Template          
    self.blockvisit(node.body, frame)
  File "/usr/local/lib/python3.4/dist-packages/jinja2/compiler.py", line 492, in blockvisit              
    self.visit(node, frame)
  File "/usr/local/lib/python3.4/dist-packages/jinja2/visitor.py", line 38, in visit                     
    return f(node, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jinja2/compiler.py", line 1140, in visit_For              
    self.blockvisit(node.body, loop_frame)
  File "/usr/local/lib/python3.4/dist-packages/jinja2/compiler.py", line 492, in blockvisit              
    self.visit(node, frame)
  File "/usr/local/lib/python3.4/dist-packages/jinja2/visitor.py", line 38, in visit                     
    return f(node, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jinja2/compiler.py", line 1169, in visit_If               
    self.visit(node.test, if_frame)
  File "/usr/local/lib/python3.4/dist-packages/jinja2/visitor.py", line 38, in visit                     
    return f(node, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/jinja2/compiler.py", line 1591, in visit_Test             
    self.fail('no test named %r' % node.name, node.lineno)                                               
  File "/usr/local/lib/python3.4/dist-packages/jinja2/compiler.py", line 427, in fail
    raise TemplateAssertionError(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateAssertionError: no test named 'eq'
```

**Comment by alexandrevicenzi** [comment]
@rpatel3001 I can't reproduce it. Also, what I have no idea of what versions of Pelican/Jinja2 you are using.

By this error, I can infer a possible place in the template that could be causing this, but since I can't reproduce I'm not 100% sure.

**Comment by rpatel3001** [comment]
Thanks for the quick response! Sorry for the lack of details, but the change seems to have fixed it. I am on Pelican 4.0.1 and Jinja2 2.8.
