### ISSUE TITLE
gettext is undefined

### ISSUE THREAD

**Issue by okelet** [alexandrevicenzi/Flex#67]
I am trying the new theme, with translations, but I can not get it to work; I get this error:

```py
CRITICAL: UndefinedError: 'gettext' is undefined
Traceback (most recent call last):
  File "/usr/bin/pelican", line 9, in <module>
    load_entry_point('pelican==3.6.3', 'console_scripts', 'pelican')()
  File "/usr/lib/python2.7/dist-packages/pelican/__init__.py", line 478, in main
    pelican.run()
  File "/usr/lib/python2.7/dist-packages/pelican/__init__.py", line 183, in run
    p.generate_output(writer)
  File "/usr/lib/python2.7/dist-packages/pelican/generators.py", line 587, in generate_output
    self.generate_pages(writer)
  File "/usr/lib/python2.7/dist-packages/pelican/generators.py", line 486, in generate_pages
    self.generate_articles(write)
  File "/usr/lib/python2.7/dist-packages/pelican/generators.py", line 364, in generate_articles
    blog=True)
  File "/usr/lib/python2.7/dist-packages/pelican/writers.py", line 211, in write_file
    override_output)
  File "/usr/lib/python2.7/dist-packages/pelican/writers.py", line 155, in _write_file
    output = template.render(localcontext)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jasensios/Dropbox/pelican-blog/themes/flex/templates/article.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/jasensios/Dropbox/pelican-blog/themes/flex/templates/base.html", line 138, in top-level template code
    <a href="{{ SITEURL }}">{{ _('Home') }}</a>
  File "/usr/lib/python2.7/dist-packages/jinja2/ext.py", line 132, in _gettext_alias
    return __context.call(__context.resolve('gettext'), *args, **kwargs)
jinja2.exceptions.UndefinedError: 'gettext' is undefined
```

This is the relevant configuration:

```py
PLUGIN_PATHS = ["plugins", "custom-plugins"]
PLUGINS = ['i18n_subsites', 'summary', 'sitemap', 'feed_summary']
JINJA_EXTENSIONS = ['jinja2.ext.i18n']

DEFAULT_LANG = 'es'
OG_LOCALE = 'es_ES'
LOCALE = 'es_ES'
I18N_TEMPLATES_LANG = 'en'
```

Also I have generated a custom translation with the commands in the wiki:

```sh
./translation.sh new es_ES
# edited with poedit
./translate.sh compile
```

**Comment by alexandrevicenzi** [comment]
Hi @okelet,

There's no translation to `es` yet. You requested to translate on Transifex, it's the better way to translate.

If you're trying to use the theme and you get this error you have 2 options.

- If you're using Windows, you just have the option to cry, I think there isn't gettext for Windows
- If you're on Linux/Unix or OS X you will need to install gettext. Just type on google how to install on your distro.

For Ubuntu I think it's `apt-get install gettext`
For OS X is `brew install gettext`, if you have HomeBrew, but Mac Ports should have too.

**Comment by okelet** [comment]
Thanks @alexandrevicenzi, while the translation is not accepted and committed, I have done it locally. Gettext is already installed; these are the packages installed and versions (defaults for Ubuntu 16.04):

```
ii  pelican                                    3.6.3-1
ii  python-pelican                             3.6.3-1
ii  gettext                                    0.19.7-2ubuntu3
ii  python-jinja2                              2.8-1
ii  python-flask                               0.10.1-2build2
ii  python-flask-babel                         0.9-2.1
```

**Comment by alexandrevicenzi** [comment]
So, is there any change that your version of jinja2 is broken?

`jinja2.exceptions.UndefinedError: 'gettext' is undefined`

The theme has nothing related. The theme just use the jinja2 extension.

Oh, I see something. Looks like you're using the versions from your S.O. Maybe you could use from PiPy.

You could use `virtualenv` to test.

**Comment by okelet** [comment]
Can't get it to work... Same error in the virtualenv:

```
(pelican-venv) jasensios@jasensioslx:~/Dropbox/pelican-blog$ pip list --format=columns
Package         Version 
--------------- --------
Babel           2.3.4   
blinker         1.4     
click           6.6     
docutils        0.13.1  
feedgenerator   1.9     
Flask           0.11.1  
Flask-Babel     0.11.1  
itsdangerous    0.24    
Jinja2          2.8     
Markdown        2.6.7   
MarkupSafe      0.23    
pelican         3.6.3   
pip             9.0.1   
pkg-resources   0.0.0   
Pygments        2.1.3   
python-dateutil 2.6.0   
pytz            2016.10 
setuptools      31.0.0  
six             1.10.0  
smartypants     1.8.6   
typogrify       2.0.7   
Unidecode       0.4.19  
Werkzeug        0.11.11 
wheel           0.30.0a0
```

I'll try using a VM and a new OS installation...

**Comment by alexandrevicenzi** [comment]
Well, try py3. I may work or not.

**Comment by okelet** [comment]
Ok, it's all about the `feed_summary` plugin (if I disable it, everything works fine). I'll have to review it to catch the error...

**Comment by alexandrevicenzi** [comment]
*Muy bueno*. You can open an issue to the project and maybe submit a PR.

So, you finished the translation to Spanish. Would you mind to send a PR?

**Comment by okelet** [comment]
I made the translation using Transifex... Is it sync'ed with Github? Or have I to download the translated, file, fork, and create a PR?

**Comment by alexandrevicenzi** [comment]
Yep, you need to send a PR, it's not synced. But I can do it later too.

**Comment by okelet** [comment]
Done!
